// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgqkbqqndasgdjxbuett.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZncWticXFuZGFzZ2RqeGJ1ZXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MjkzNTcsImV4cCI6MjA3MDQwNTM1N30.8nWUaOKchfrfeHdMqiaPZiDeUf-0b7pFnGviuH7HR78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});